version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    env_file:
      - .env
    volumes:
      - ./docker/db/${PROJECT_NAME}.sql:/docker-entrypoint-initdb.d/${PROJECT_NAME}.sql

  app:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    environment:
      DATABASE_URL: "${DB_DRIVER}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}"
    depends_on:
      - db
